### ISSUE TITLE
Can we have a date for discussing the project? :)

### ISSUE THREAD

**Issue by cleydyr** [waltinhoporfi/sale_taxes#1]

**Comment by waltinhoporfi** [comment]
Of course, can it be tomorrow?


Atenciosamente,

Walter Porfírio Silveira
Tel: (81) 996919934
Recife PE

________________________________
De: Cleydyr Bezerra de Albuquerque <notifications@github.com>
Enviado: quinta-feira, 10 de dezembro de 2020 15:44
Para: waltinhoporfi/sale_taxes <sale_taxes@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [waltinhoporfi/sale_taxes] Can we have a date for discussing the project? :) (#1)

**Comment by cleydyr** [comment]
Oops! Tomorrow I'll be doing corporate volunteer work. Can you propose a time you're comfortable with?

Thanks!

**Comment by waltinhoporfi** [comment]
What is your availability?


Atenciosamente,

Walter Porfírio Silveira
Tel: (81) 996919934
Recife PE

________________________________
De: Cleydyr Bezerra de Albuquerque <notifications@github.com>
Enviado: quinta-feira, 10 de dezembro de 2020 18:56
Para: waltinhoporfi/sale_taxes <sale_taxes@noreply.github.com>
Cc: Walter Porfirio <walterporfirio@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [waltinhoporfi/sale_taxes] Can we have a date for discussing the project? :) (#1)


Oops! Tomorrow I'll be doing corporate volunteer work. Can you propose a time you're comfortable with?

Thanks!

**Comment by cleydyr** [comment]
My nearest slot is Tuesday (Dec. 15th) at 9 am. Is it okay for you?

**Comment by waltinhoporfi** [comment]
Closed, Tuesday at 9 am.


Atenciosamente,

Walter Porfírio Silveira
Tel: (81) 996919934
Recife PE

________________________________
De: Cleydyr Bezerra de Albuquerque <notifications@github.com>
Enviado: quinta-feira, 10 de dezembro de 2020 19:15
Para: waltinhoporfi/sale_taxes <sale_taxes@noreply.github.com>
Cc: Walter Porfirio <walterporfirio@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [waltinhoporfi/sale_taxes] Can we have a date for discussing the project? :) (#1)


My nearest slot is Tuesday (Dec. 15th) at 9 am. Is it okay for you?

**Comment by cleydyr** [comment]
Great! I'll send you a Google Calendar invitation. There's a link to a Google Meet video call in it, so stay tuned. :+1: 

Thank you very much!
